<a href="https://colab.research.google.com/github/DataScience-2021/Guia-Completo-IA-01-Python/blob/main/Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrizes

In [1]:
import numpy as np

In [2]:
matriz = np.array([[21, 31, 11,3,4,5,6], 
                   [4, 5, 7,6,7,5,6]])

In [3]:
matriz

array([[21, 31, 11,  3,  4,  5,  6],
       [ 4,  5,  7,  6,  7,  5,  6]])

In [4]:
matriz.shape

(2, 7)

In [5]:
matriz[0]

array([21, 31, 11,  3,  4,  5,  6])

In [6]:
matriz[1]

array([4, 5, 7, 6, 7, 5, 6])

In [7]:
matriz[0][2]

11

In [8]:
matriz[1][2]

7

In [9]:
matriz.shape

(2, 7)

In [12]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[1][j])  

[21 31 11  3  4  5  6]
4
5
7
6
7
5
6
[4 5 7 6 7 5 6]
4
5
7
6
7
5
6
