## Minerando Dados - Data Science do Zero ##
## Capítulo 06 - Machine Learning em Produção 

## Persistindo Objetos em Disco ##

#### Importando as bibliotecas necessárias

In [40]:
import pickle
from sklearn.externals import joblib
import numpy as np
import _pickle as cPickle

#### Criação do objeto do tipo lista.

In [41]:
lista = [1500,1234,567,14]

#### Criação do arquivo em disco.

In [42]:
arquivo = open('lista.pkl','wb')

#### Persistindo o objeto em disco.

In [43]:
pickle.dump(lista,arquivo)

In [44]:
arquivo.close()

In [45]:
!ls

array.npy   lista3.joblib  model.pkl
lista2.npy  lista.pkl	   persistencia-objetos-disco.ipynb
lista3.gz   loan.csv	   persistindo-modelo-machine-learning-disco.ipynb


#### Carregando o objeto a partir do disco para a memória.

In [46]:
arquivo2 = open('lista.pkl','rb')

In [47]:
lista2 = pickle.load(arquivo2)

In [48]:
arquivo2.close()

In [49]:
lista2

[1500, 1234, 567, 14]

## Persistindo objetos utilizando o Numpy

#### Definindo o array

In [50]:
x = np.arange(10)

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Persistindo o array em disco

In [52]:
np.save('array', x)

#### Listando os arquivos em disco

In [57]:
!ls

array.npy   lista3.joblib  model.pkl
lista2.npy  lista.pkl	   persistencia-objetos-disco.ipynb
lista3.gz   loan.csv	   persistindo-modelo-machine-learning-disco.ipynb


#### Carregando o objeto a partir do disco para a memória.

In [54]:
x2 = np.load('array.npy')

In [55]:
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Persistindo a lista criada anteriormente em disco

In [56]:
np.save('lista2.npy',lista2)

#### Carregando o objeto a partir do disco para a memória.

In [58]:
lista3 = np.load('lista2.npy')

In [59]:
lista3

array([1500, 1234,  567,   14])

#### Verificando o tipo do objeto criado.

In [60]:
type(lista3)

numpy.ndarray

## Persistindo objetos utilizando o Joblib

#### Persistindo a lista criada anteriormente em disco.

In [61]:
joblib.dump(lista3,'lista3.joblib')

['lista3.joblib']

#### Listando os arquivos em disco

In [62]:
!ls

array.npy   lista3.joblib  model.pkl
lista2.npy  lista.pkl	   persistencia-objetos-disco.ipynb
lista3.gz   loan.csv	   persistindo-modelo-machine-learning-disco.ipynb


#### Persistindo a lista criada anteriormente em disco utilizando compressão.

In [63]:
joblib.dump(lista3,'lista3.gz',compress=True)

['lista3.gz']

#### Carregando o objeto a partir do disco para a memória.

In [64]:
lista4 = joblib.load('lista3.gz')

In [65]:
lista4

array([1500, 1234,  567,   14])