# Amostragem

## Carregamento da base de dados

In [2]:
import pandas as pd
import random
import numpy as np

In [61]:
dataset = pd.read_csv('census.csv')

In [6]:
dataset.shape

(8530, 15)

In [7]:
dataset.head()

age          workclass  final-weight  ... hour-per-week  native-country  income
0   39          State-gov         77516  ...            40   United-States   <=50K
1   50   Self-emp-not-inc         83311  ...            13   United-States   <=50K
2   38            Private        215646  ...            40   United-States   <=50K
3   53            Private        234721  ...            40   United-States   <=50K
4   28            Private        338409  ...            40            Cuba   <=50K

[5 rows x 15 columns]

In [8]:
dataset.tail()

age          workclass  ...  native-country  income
8525   50   Self-emp-not-inc  ...   United-States    >50K
8526   29            Private  ...   United-States   <=50K
8527   23            Private  ...   United-States   <=50K
8528   64            Private  ...   United-States   <=50K
8529   70          Local-gov  ...   United-States      >5

[5 rows x 15 columns]

## Amostragem aleatória simples

In [9]:
df_amostra_aleatoria_simples = dataset.sample(n = 100, random_state = 1)

In [10]:
df_amostra_aleatoria_simples.shape

(100, 15)

In [11]:
df_amostra_aleatoria_simples.head()

age          workclass  ...  native-country  income
685    34            Private  ...   United-States   <=50K
4802   25            Private  ...   United-States   <=50K
5619   32            Private  ...         Ireland   <=50K
5099   46          Local-gov  ...   United-States    >50K
2939   37   Self-emp-not-inc  ...   United-States   <=50K

[5 rows x 15 columns]

In [12]:
def amostragem_aleatoria_simples(dataset, amostras):
  return dataset.sample(n = amostras, random_state=1)

In [13]:
df_amostra_aleatoria_simples = amostragem_aleatoria_simples(dataset, 100)
df_amostra_aleatoria_simples.shape

(100, 15)

In [14]:
df_amostra_aleatoria_simples.head()

age          workclass  ...  native-country  income
685    34            Private  ...   United-States   <=50K
4802   25            Private  ...   United-States   <=50K
5619   32            Private  ...         Ireland   <=50K
5099   46          Local-gov  ...   United-States    >50K
2939   37   Self-emp-not-inc  ...   United-States   <=50K

[5 rows x 15 columns]

## Amostragem sistemática

In [15]:
dataset.shape

(8530, 15)

In [16]:
len(dataset) // 100

85

In [17]:
random.seed(1)
random.randint(0, 170)

34

In [18]:
68 + 325

393

In [ ]:
393 + 325

718

In [19]:
np.arange(68, len(dataset), step = 325)

array([  68,  393,  718, 1043, 1368, 1693, 2018, 2343, 2668, 2993, 3318,
       3643, 3968, 4293, 4618, 4943, 5268, 5593, 5918, 6243, 6568, 6893,
       7218, 7543, 7868, 8193, 8518])

In [20]:
def amostragem_sistematica(dataset, amostras):
  intervalo = len(dataset) // amostras
  random.seed(1)
  inicio = random.randint(0, intervalo)
  indices = np.arange(inicio, len(dataset), step = intervalo)
  amostra_sistematica = dataset.iloc[indices]
  return amostra_sistematica

In [21]:
df_amostra_sistematica = amostragem_sistematica(dataset, 100)
df_amostra_sistematica.shape

(101, 15)

In [22]:
df_amostra_sistematica.head()

age          workclass  ...  native-country  income
17    32            Private  ...   United-States   <=50K
102   47   Self-emp-not-inc  ...   United-States   <=50K
187   53                  ?  ...   United-States   <=50K
272   50   Self-emp-not-inc  ...   United-States   <=50K
357   40            Private  ...   United-States    >50K

[5 rows x 15 columns]

## Amostragem por grupos

In [23]:
len(dataset) / 10

853.0

In [24]:
dataset.shape

(8530, 15)

In [25]:
grupos = []
id_grupo = 0
contagem = 0
for _ in dataset.iterrows():
  grupos.append(id_grupo)
  contagem += 1
 # if contagem > 3256:
  if contagem > 853:
    contagem = 0
    id_grupo += 1

In [26]:
print(grupos)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [27]:
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([854, 854, 854, 854, 854, 854, 854, 854, 854, 844]))

In [28]:
np.shape(grupos),print('Hello'),dataset.shape

Hello


((8530,), None, (8530, 15))

In [29]:
np.shape(grupos), dataset.shape

((8530,), (8530, 15))

In [30]:
dataset['grupo'] = grupos

In [31]:
dataset.head()

age          workclass  final-weight  ...  native-country  income grupo
0   39          State-gov         77516  ...   United-States   <=50K     0
1   50   Self-emp-not-inc         83311  ...   United-States   <=50K     0
2   38            Private        215646  ...   United-States   <=50K     0
3   53            Private        234721  ...   United-States   <=50K     0
4   28            Private        338409  ...            Cuba   <=50K     0

[5 rows x 16 columns]

In [32]:
dataset.tail()

age          workclass  final-weight  ...  native-country  income grupo
8525   50   Self-emp-not-inc         57758  ...   United-States    >50K     9
8526   29            Private        207064  ...   United-States   <=50K     9
8527   23            Private        193090  ...   United-States   <=50K     9
8528   64            Private        151364  ...   United-States   <=50K     9
8529   70          Local-gov         88638  ...   United-States      >5     9

[5 rows x 16 columns]

In [33]:
random.randint(0, 9)

9

In [34]:
df_agrupamento = dataset[dataset['grupo'] == 7]
df_agrupamento.shape

(854, 16)

In [35]:
df_agrupamento['grupo'].value_counts()

7    854
Name: grupo, dtype: int64

In [36]:
def amostragem_agrupamento(dataset, numero_grupos):
  intervalo = len(dataset) / numero_grupos

  grupos = []
  id_grupo = 0
  contagem = 0
  for _ in dataset.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > intervalo:
      contagem = 0
      id_grupo += 1

  dataset['grupo'] = grupos
  random.seed(1)
  grupo_selecionado = random.randint(0, numero_grupos)
  return dataset[dataset['grupo'] == grupo_selecionado]

In [ ]:
#len(dataset) / 325
len(dataset) // 325

26

In [ ]:
325 * 100

32500

In [37]:
df_amostra_agrupamento = amostragem_agrupamento(dataset, 325)
df_amostra_agrupamento.shape, df_amostra_agrupamento['grupo'].value_counts()

((27, 16), 68    27
 Name: grupo, dtype: int64)

In [38]:
df_amostra_agrupamento.head()

age workclass  final-weight  ...  native-country  income grupo
1836   58   Private        312131  ...   United-States   <=50K    68
1837   70   Private         30713  ...   United-States   <=50K    68
1838   30   Private        246439  ...   United-States   <=50K    68
1839   45   Private        338105  ...     Philippines   <=50K    68
1840   23   Private        228243  ...   United-States   <=50K    68

[5 rows x 16 columns]

In [39]:
df_amostra_agrupamento

age          workclass  final-weight  ...  native-country  income grupo
1836   58            Private        312131  ...   United-States   <=50K    68
1837   70            Private         30713  ...   United-States   <=50K    68
1838   30            Private        246439  ...   United-States   <=50K    68
1839   45            Private        338105  ...     Philippines   <=50K    68
1840   23            Private        228243  ...   United-States   <=50K    68
1841   34          Local-gov         62463  ...   United-States   <=50K    68
1842   38            Private         31603  ...   United-States   <=50K    68
1843   24            Private        165054  ...   United-States   <=50K    68
1844   53            Private        121618  ...   United-States   <=50K    68
1845   45        Federal-gov        273194  ...   United-States   <=50K    68
1846   21                  ?        163665  ...   United-States   <=50K    68
1847   21            Private        538319  ...     Puerto-Rico   <=50K    68
1848   34            Private        238246  ...   United-States   <=50K    68
1849   32       Self-emp-inc        244665  ...   United-States    >50K    68
1850   21            Private        131811  ...   United-States   <=50K    68
1851   63                  ?        231777  ...   United-States   <=50K    68
1852   23            Private        156807  ...   United-States   <=50K    68
1853   28            Private        236861  ...   United-States   <=50K    68
1854   29   Self-emp-not-inc        229842  ...   United-States   <=50K    68
1855   25          Local-gov        190057  ...   United-States   <=50K    68
1856   44          State-gov         55076  ...   United-States   <=50K    68
1857   18            Private        152545  ...   United-States   <=50K    68
1858   26            Private        153434  ...   United-States   <=50K    68
1859   47          Local-gov        171095  ...   United-States    >50K    68
1860   23            Private        239322  ...   United-States   <=50K    68
1861   46            Private        138999  ...   United-States   <=50K    68
1862   61          Local-gov         95450  ...   United-States    >50K    68

[27 rows x 16 columns]

## Amostra estratificada

In [66]:
from sklearn.model_selection import StratifiedShuffleSplit

In [67]:
dataset.shape

(32561, 15)

In [68]:
dataset['income'].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [69]:
dataset['income'].head

<bound method NDFrame.head of 0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
          ...  
32556     <=50K
32557      >50K
32558     <=50K
32559     <=50K
32560      >50K
Name: income, Length: 32561, dtype: object>

In [44]:
#7841 / len(dataset), 24720 / len(dataset)
6495 / len(dataset), 2034 / len(dataset)

(0.761430246189918, 0.2384525205158265)

In [ ]:
# 0.2408095574460244 + 0.7591904425539756
0.761430246189918 + 0.2384525205158265

0.9998827667057444

In [45]:
100 / len(dataset)

0.011723329425556858

In [70]:
#@title Texto de título predefinido
split = StratifiedShuffleSplit(test_size=0.1)
for x, y in split.split(dataset, dataset['income']):
  #for x,y in split.split(dataset, 100):
  df_x = dataset.iloc[x]
  df_y = dataset.iloc[y]

In [71]:
df_x.shape, df_y.shape

((29304, 15), (3257, 15))

In [72]:
df_y.head()

age          workclass  ...  native-country  income
21023   32            Private  ...   United-States    >50K
14295   56          Local-gov  ...   United-States   <=50K
30085   25            Private  ...   United-States   <=50K
13696   82   Self-emp-not-inc  ...            Cuba   <=50K
20713   55          State-gov  ...   United-States   <=50K

[5 rows x 15 columns]

In [73]:
df_y['income'].value_counts()

 <=50K    2473
 >50K      784
Name: income, dtype: int64

In [74]:
def amostragem_estratificada(dataset, percentual):
  split = StratifiedShuffleSplit(test_size=percentual, random_state=1)
  for _, y in split.split(dataset, dataset['income']):
    df_y = dataset.iloc[y]
  return df_y

In [75]:
df_amostra_estratificada = amostragem_estratificada(dataset, 0.0030711587481956942)
df_amostra_estratificada.shape

(100, 15)

## Amostragem de reservatório

In [50]:
stream = []
for i in range(len(dataset)):
  stream.append(i)

In [51]:
print(stream)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [52]:
def amostragem_reservatorio(dataset, amostras):
  stream = []
  for i in range(len(dataset)):
    stream.append(i)

  i = 0
  tamanho = len(dataset)

  reservatorio = [0] * amostras
  for i in range(amostras):
    reservatorio[i] = stream[i]

  while i < tamanho:
    j = random.randrange(i + 1)
    if j < amostras:
      reservatorio[j] = stream[i]
    i += 1

  return dataset.iloc[reservatorio]
  

In [53]:
df_amostragem_reservatorio = amostragem_reservatorio(dataset, 100)
df_amostragem_reservatorio.shape

(100, 16)

In [54]:
df_amostragem_reservatorio.head()

age      workclass  final-weight  ...  native-country  income grupo
771    37        Private        327323  ...       Guatemala   <=50K    28
5410   21        Private        146499  ...   United-States   <=50K   200
5352   26        Private        108542  ...   United-States   <=50K   198
816    41        Private        254440  ...   United-States   <=50K    30
6055   45   Self-emp-inc        160440  ...   United-States   <=50K   224

[5 rows x 16 columns]

## Comparativo dos resultados

In [55]:
dataset['age'].mean()

38.46225087924971

In [56]:
df_amostra_aleatoria_simples['age'].mean()

36.56

In [57]:
df_amostra_sistematica['age'].mean()

37.722772277227726

In [58]:
df_amostra_agrupamento['age'].mean()

36.370370370370374

In [76]:
df_amostra_estratificada['age'].mean()

36.9

In [60]:
df_amostragem_reservatorio['age'].mean()

38.21